# Konfigurasjonsfil for CI
language: ruby
rvm:
  - 3.4.3

before_install:
  - gem update --system
  - gem install bundler

# Sørg for at filen er kjørbar
before_script:
  - chmod +x ./script/cibuild.sh

script: ./script/cibuild.sh

# Hvilke branches vi kjører CI på
branches:
  only:
    - master
    - /pages-(.*)/

# Optimalisering av byggetid
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

# Deps
addons:
  apt:
    packages:
      - libcurl4-openssl-dev


sudo: false

cache: bundler

notifications:
  email: false
